import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body style={{ minHeight: "100vh", backgroundColor: "#f8fafc", color: "#22223b" }}>
        <header
          style={{
            backgroundColor: "#e2e8f0",
            color: "#22223b",
            padding: "16px 24px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <h1 style={{ margin: 0, fontSize: "20px" }}>TaskFlow</h1>
          <nav style={{ display: "flex", gap: "16px" }}>
            <span>Dashboard</span>
            <span>Tareas</span>
            <span>Proyectos</span>
          </nav>
        </header>
        <main style={{ maxWidth: "960px", margin: "0 auto", padding: "24px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}
